// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vybyyhmaaiurjrbusqch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5Ynl5aG1hYWl1cmpyYnVzcWNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDQyMTAsImV4cCI6MjA3MDkyMDIxMH0.4xgrMlFd5Vzcz51sQwVs3wLIp3oBjnS2O4nciA5QzmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});